[build]
  command = """
    # Install Flutter
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:$PWD/flutter/bin"
    
    # Enable web support
    flutter config --enable-web
    
    # Get dependencies
    flutter pub get
    
    # Build web app
    flutter build web
  """
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18.17.0"